name = "cal"
main = "src/index.ts"
compatibility_date = "2026-05-17"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "cal.fly.pm"
custom_domain = true

[vars]
AI_GATEWAY_ACCOUNT_ID = "85d376fc54617bcb57185547f08e528b"
AI_GATEWAY_NAME = "x"
BETTER_AUTH_URL = "https://cal.fly.pm"
BETTER_AUTH_TRUSTED_ORIGINS = "https://cal.fly.pm,https://cal.lazee.workers.dev"
DP_WEBHOOK_URL = "https://alex.coffee/api/sync/webhook"
REALTIMEKIT_APP_ID = "806174ec-d6d3-479b-a02a-9db9da2b6333"
INVITE_EMAIL_FROM = "calendar@fly.pm"

[ai]
binding = "AI"

[[send_email]]
name = "INVITE_EMAIL"

[[d1_databases]]
binding = "DB"
database_name = "cal-db"
database_id = "72c116f4-ba2c-4520-bafb-538e7ffe741e"

[[d1_databases]]
binding = "DP_DB"
database_name = "daily-planner-db"
database_id = "3afbe37d-947e-4f92-bbd9-db3be5065ea8"

[triggers]
crons = ["0 9 * * *"]

[[r2_buckets]]
binding = "CAL_ASSETS"
bucket_name = "cal-assets"

[[kv_namespaces]]
binding = "CAL_CACHE"
id = "1e12c8646ed645d98af9c0b5357351fb"

[[vectorize]]
binding = "EMBEDDINGS_INDEX"
index_name = "cal-embeddings"
